name: Playwright Tests

on:
  #push:
    #branches: [Develop]  # Automatically runs when pushing to 'develop'
  #pull_request:
    #branches: [Develop]  # Runs on PRs to 'develop'
  workflow_dispatch:  # Allows manual execution with dropdown
    inputs:
      test_type:
        description: "Select which tests to run"
        required: true
        default: "all"
        type: choice
        options:
          - all
          - e2e

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Selected Playwright Tests
      run: npx playwright test tests/UI/EndtoEndpomjson.spec.js

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30